### ISSUE TITLE
Lifestyle Music don't speedup progress in singleplayer

### ISSUE THREAD

**Issue by W1nKille3r** [Angry362/Lifestyle-Mod-Project-Zomboid-#10]
As I understood the result of experience is accumulated only in real time, when scrolling through time the character finishes playing faster than the experience is gained.

So to try out the mod to level 10 with music. I have to choose trait otherwise it will be incredibly long in real time.

**The mod should initially give experience when rewinding time. This is unacceptable for singleplayer**

**Comment by Angry362** [comment]
Hello, if I understood you correctly you sped up time while playing the song in order to grind xp? I can look into increasing the xp adjustment rate based on game speed, but in the meantime please understand that in order to get more xp try playing when your character is well rested, not stressed or unhappy and not embarrassed. Some traits like keen hearing will help level up the skill faster, while others like hard of hearing and tone-deaf will cause it to level up slower.

**Comment by W1nKille3r** [comment]
> Hello, if I understood you correctly you sped up time while playing the song in order to grind xp? I can look into increasing the xp adjustment rate based on game speed, but in the meantime please understand that in order to get more xp try playing when your character is well rested, not stressed or unhappy and not embarrassed. Some traits like keen hearing will help level up the skill faster, while others like hard of hearing and tone-deaf will cause it to level up slower.

You closed the last thread, you should change the name of this section since I thought it was the effectiveness of the skills themselves.

**Comment by Angry362** [comment]
It changes the effectiveness of the skill as well. I'll improve the option's description to make it clearer, thank you for the feedback :)

**Comment by Angry362** [comment]
Considering the absence of further interaction I'll be closing the issue now, but please let me know should you need help in the future :)
