### ISSUE TITLE
Guitar playing\meditation end instantly

### ISSUE THREAD

**Issue by Xenomorf1996** [Angry362/Lifestyle-Mod-Project-Zomboid-#13]
For some reason, neither of these two activities work for me. Perhaps there is a mod conflict, but I'm not sure yet. I am sending a partial text file with logs directly related to the mod. Debug\admin mode is not active.

[Lifestyle_logs.txt](https://github.com/Angry362/Lifestyle-Mod-Project-Zomboid-/files/13629143/Lifestyle_logs.txt)

**Comment by Angry362** [comment]
Hello! This partial log doesn't tell me much, but this line is worth of study:

`[10-12-23 23:33:10.089] LOG  : General     , 1702240390089> bugged action, cleared queue 	ISInventoryTransferAction.`

Do you have any mod that messes with the vanilla transfer item action? In any case, please do send me your full log as it will be able to tell us more.

**Comment by Xenomorf1996** [comment]
Yes, sure. Here are the full logs. It is quite possible that the reason lies in mod conflicts - I have to test different options for the local server, and sometimes this leads to unplayable situations.
[11-12-23_21-16-35_DebugLog.txt](https://github.com/Angry362/Lifestyle-Mod-Project-Zomboid-/files/13639631/11-12-23_21-16-35_DebugLog.txt)

**Comment by Angry362** [comment]
At a first glance I couldn't find anything wrong specifically with lifestyle, so it seems likely to be a mod conflict. A few errors that may be worth of notice:

`[11-12-23 21:18:41.317] LOG  : General     , 1702318721317> Index 800 out of bounds for length 800.
[11-12-23 21:18:41.318] ERROR: General     , 1702318721318> java.lang.ArrayIndexOutOfBoundsException: Index 800 out of bounds for length 800.`

It couldn't point me to the source but out of bounds always happens when arrays are set incorrectly or when a function has too many arrays. Out of bounds is infamous for leading to all sorts of issues.

`attempted index: addProfession of non-table: null.
[11-12-23 21:18:27.403] LOG  : General     , 1702318707403> 
function: professions.lua -- file: professions.lua line # 1 | MOD: More Professions.
[11-12-23 21:18:27.403] ERROR: General     , 1702318707403> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: addProfession of non-table: null at KahluaThread.tableget line:1689..`

Some issue coming from more professions mod, failed to get the table for addProfession.

I'd suggest you to trim your mod list, even better if you clean your mod folder.

**Comment by Xenomorf1996** [comment]
Well, I guess it's time to tell my friends we need to shorten our mod list a bit...
Thank you for your help!

**Comment by Angry362** [comment]
No problem! :)
