### ISSUE TITLE
mood framework and lifestyle conflict

### ISSUE THREAD

**Issue by Sniper4721** [Angry362/Lifestyle-Mod-Project-Zomboid-#15]
having these at same time will result constant errors which is almost inevitable to catch, thanks to [errorMagnifier](https://steamcommunity.com/sharedfiles/filedetails/?id=2896041179&searchtext=error), this allowed me to diagnose and identify errors, however, it is too long to read (14.0 MB), and I copied some logs with errorMagnifier into my notepad instead, I wanted to say it is complete impossible to play with [weather moodle](https://steamcommunity.com/sharedfiles/filedetails/?id=2920735875&searchtext=weather+moodle) and [mood framework](https://steamcommunity.com/sharedfiles/filedetails/?id=2859296947&searchtext=weather+moodle) together due to moodle lua conflict. if you believe it was by mood framework instead, please contact them to cooperate or I pass to them about conflict instead.

[sniperak472-pzlifestylelogs.txt](https://github.com/Angry362/Lifestyle-Mod-Project-Zomboid-/files/13657126/pzlifestylelogs.txt)
[sniperak472-console.txt](https://github.com/Angry362/Lifestyle-Mod-Project-Zomboid-/files/13657127/console.txt)

**Comment by Sniper4721** [comment]
shortened [console.txt](https://github.com/Angry362/Lifestyle-Mod-Project-Zomboid-/files/13658667/console.txt)

**Comment by Angry362** [comment]
Hi! Having looked at the logs I believe it's the exact same issue as reported here:
https://github.com/Angry362/Lifestyle-Mod-Project-Zomboid-/issues/2

The error attempted index: MoodlePriority of non-table: null happens when the code can't find the sandbox options for lifestyle. The sandbox options were added in patch 0.2 in august. Earlier versions lacked the sandbox options and there were several alternate versions of lifestyle made back when I removed the mod in June, having any of these versions downloaded (or modpacks that ripped the contents of the mod) will cause this issue.

You have to unsubscribe from your mods and clean your mod folder OR find the older version of lifestyle installed in your mods folder, unsub from it and then delete it. Maybe searching for "lifestyle" in your mod folders can help you find it, "InstrumentContextMenu" is also a file name that the current and old versions share and could help you find them that way.

**Comment by Sniper4721** [comment]
hmm addon ID?

**Comment by Angry362** [comment]
In this case it wouldn't be an addon, but as explained an older version of lifestyle either in a modpack or an alternate version not uploaded by me, so unfortunately I wouldn't know the IDs. For both cases the solution was in the previous comment:
"You have to unsubscribe from your mods and clean your mod folder OR find the older version of lifestyle installed in your mods folder, unsub from it and then delete it. Maybe searching for "lifestyle" in your mod folders can help you find it, "InstrumentContextMenu" is also a file name that the current and old versions share and could help you find them that way."

**Comment by Angry362** [comment]
Due to the lack of response I'll presume the issue has been resolved, please do open a new issue should you need help again in the future :)
