### ISSUE TITLE
Crawlers disappear when Lifestyle is used with mod 'Random Zombies - Day and Night'

### ISSUE THREAD

**Issue by Bibibububobo** [Angry362/Lifestyle-Mod-Project-Zomboid-#5]
Hi, I just found a surprising incompatibility with the mod 'Random Zombies - Day and Night' (2888099799) about crawlers status.

To Reproduce
Install your mod and the one listed above. Have a Z distribution in this last mod with some crawlers (default have some). But they wont appear ingame.

Expected behavior
Crawlers should exist ingame when they are in the distrib. I can only guess animations from Lifestyle do override the status of crawlers the second mod applies.

Specification (please complete the following information):
    Game Version: latest (Steam)
    Game mode: MP on dedicated server. Didnt try on SP.
    SandboxVars block for the mod: default one. Well it is more visible with a high crawler amount set, of course.

**Comment by Angry362** [comment]
Hi Bibi, sorry you're having issues with the game. I play with random zombies as well and have no issues with crawlers spawning. Are you sure this is related to lifestyle? I haven't checked the code of random zombies, but I can say without any shadow of doubt that lifestyle makes no use of the IsoZombie class, or zombie spawning or anything related to zombies. Players are a different class from zombies and require several different triggers for any of the animations to play out (plus crawling is a type and not merely an animation). It's more likely that the issue is either from random zombies itself or another mod that makes changes to zombies and has overlapping functions with random zombies.

**Comment by Angry362** [comment]
![Screenshot_20230928-011003~2](https://github.com/Angry362/Lifestyle-Mod-Project-Zomboid-/assets/138312991/0eafc862-2230-4eb9-8839-21da156f1d0e)
Considering the lack of response and the new developments concerning this issue in the random zombie's github I'll be closing this thread. Please do reach out again should you need help in the future.
