### ISSUE TITLE
Multiple errors + no xp point

### ISSUE THREAD

**Issue by Urlynatort** [Angry362/Lifestyle-Mod-Project-Zomboid-#9]
1) Related to the music and meditation system.
2) When i sit my character, the game create an error, or just when i left-click anywhere on my screen.
3) It happens even when just the Lifestyle mod is active.

But i'va played with your mod months ago and i loved it, the work you've done is amazing
And i'm really sorry, i've tried to find the console.txt file but it seems i'm really dumb

**Comment by Angry362** [comment]
Hey Urlynatort! I believe this may be the source of the issue:
[FAQ Question 5 and 6](https://github.com/Angry362/Lifestyle-Mod-Project-Zomboid-/wiki/F.A.Q.#5-q-i-dont-see-errors-but-why-cant-i-interact-with-anything-from-the-new-update-in-singleplayer-or-why-am-i-getting-duplicated-lifestyle-skills-in-servers-or-getting-file-dont-exist-messages)

If your OS is Windows then the log should be under YOURDRIVER:\Users\YOURUSERNAME\Zomboid

But since you mentioned errors even while playing with only this mod then the most likely reason for the errors is having files from an older version of the mod messing things up, could be from an old reupload or a modpack and they can cause issues even if not enabled (they'll still overwrite files from the updated mod). It's probably best to clean your mod folders.


To clean the mods' folder I'd recommend purging the workshop subscription list and then making sure that the folders with the game's ID is clean of mods, you can find the folders in:
```
\Steam\steamapps\workshop\content\
and
\Steam\steamapps\common\ProjectZomboid\steamapps\workshop\content\
(do not delete the game's ID folder, only any mod folder that might be inside)
```
Unless you know the exact id for the modpack or reupload installed, this is unfortunately the only way to guarantee that a reupload or modpack isn't overwriting Lifestyle.

**Comment by Urlynatort** [comment]
I've cleaned the the mod like you said and everything work now, thank you SOOOOO much

**Comment by Angry362** [comment]
I'm glad that it worked! Closing the issue now, please let me know should you need help in the future :)
